<../../mkconfig

TARG=\
	ascii85decode.dis\
	asciihexdecode.dis\
	cascadefilter.dis\
	lzwdecode.dis\
	nullfilter.dis\
	pdfinflate.dis\
	pdfread.dis

MODULES=\

SYSMODULES=\
	sys.m\
	bufio.m\
	pdfread.m\

DISBIN=$ROOT/dis/lib

<$ROOT/mkfiles/mkdis
