<../../mkconfig

DIRS=\
	pdf\

TARG=\
	filtrate.dis\
	readline.dis\

SYSMODULES=\
	arg.m\
	bufio.m\
	daytime.m\
	draw.m\
	keyring.m\
	string.m\
	sys.m\
	pdfread.m\

DISBIN=$ROOT/dis

<$ROOT/mkfiles/mkdis
<$ROOT/mkfiles/mksubdirs
